name: CI test app

on: [push]
#pull_request
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --workspaces

  test:
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: npm test --workspaces --if-present

