name: Node.js CI

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --prefix /back ci
      # - run: npm run build --if-present
      - run: npm --prefix /back/tests tests

      # - name: Install dependencies
      #   run: npm install

      # - name: Test
      #   run: npm test