name: Node.js Install

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --workspaces
      - name: Test
        run: npm test --workspaces --if-present
